name = "exception-notify-workspace"
compatibility_date = "2024-01-01"
pages_build_output_dir = "web/dist"

[build]
command = "cd web && npm install && npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = "web/dist"
