name = "exception-notify-worker"
main = "./.open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat","global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_BUILD_SHA = "${GIT_COMMIT_SHA}"

[[kv_namespaces]]
binding = "CODE_MAP"
id = "${KV_NAMESPACE_ID}"

[[d1_databases]]
binding = "DB"
database_name = "exception-notify-db"
database_id = "${D1_DATABASE_ID}"


[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
